#!/bin/bash
if [ $# -lt 1 ]
then
echo "Usage: $0  repo name to be created on github"
exit
fi
curl -u 'herotest' https://api.github.com/user/repos -d "{\"name\":\"$1\"}";
git init;
git remote add origin git@github.com:herotest/$1.git;

#http://stackoverflow.com/questions/2423777/is-it-possible-to-create-a-remote-repo-on-github-from-the-cli-without-ssh
